name: aquaharvest_mobile
description: AquaHarvest - Rainwater Harvesting Assessment Mobile App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  go_router: ^12.1.3
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9

  # HTTP & API
  dio: ^5.3.4
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  graphql_flutter: ^5.1.2

  # Local Storage & Cache
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Location & Maps
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1

  # Camera & Image
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3

  # Authentication & Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

  # UI Components & Animation
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0

  # Charts & Visualization
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.2.7

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2

  # Firebase (optional for analytics)
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  freezed: ^2.4.6

  # Linting & Analysis
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700